import type { WidgetSettings } from "../types";

export const DEFAULT_WIDGET_SETTINGS: WidgetSettings = {
  displayName: null,
  welcomeTitle: "How can we help?",
  welcomeMessage: "Send us a message and we'll get back to you as soon as we can.",
  headerSubtitle: "We typically reply within a few minutes",
  quickPrompts: ["I need help with my order", "Billing question", "Talk to an agent"],
  accentColor: "#FF1E2D",
  panelBackground: "#ffffff",
  chatBackground: "#f4f5f7",
  textColor: "#111111",
  mutedTextColor: "#5c6370",
  position: "bottom-right",
  launcherStyle: "circle",
  requirePreChatName: false,
  requirePreChatEmail: false,
  preChatNameLabel: "Your name",
  preChatEmailLabel: "Your email",
  launcherIconUrl: null,
  avatarUrl: null,
  businessHoursEnabled: false,
  businessHoursStart: 9,
  businessHoursEnd: 17,
  businessHoursTimezone: "local",
  offlineTitle: "We're away right now",
  offlineMessage: "Leave your details and we'll get back to you when we're online.",
  proactiveEnabled: false,
  proactiveDelaySeconds: 15,
  proactiveMessage: "Need help? Chat with us!",
  csatEnabled: true,
  csatPrompt: "How was your chat experience?",
  fileUploadEnabled: true,
  defaultLocale: "en",
  locales: {},
  widgets: {},
};
